"""Compatibility facade for the extracted online-play package."""

from online_play.match_flow import (
    CRITICAL_MESSAGE_TYPES,
    LATEST_ONLY_MESSAGE_TYPES,
    UNRELIABLE_MESSAGE_TYPES,
    MatchSettings,
    MatchStartPayload,
    NetworkPlayerSetup,
    build_game_start_payload,
    build_player_setup_payload,
    parse_game_start_message,
    parse_player_setup_message,
)
from online_play.session import (
    DEFAULT_PORT,
    DISCOVERY_HOST_MAX_AGE,
    DISCOVERY_MAGIC,
    DISCOVERY_PORT,
    DiscoveredHost,
    LanGameFinder,
    NetworkClient,
    NetworkHost,
    NetworkManager,
    get_local_ip,
    get_public_ip,
)
from online_play.transport import (
    CONNECTION_TIMEOUT,
    FRAGMENT_RAW_CHUNK_BYTES,
    FRAGMENT_TTL_SECONDS,
    GAME_UDP_PORT_OFFSET,
    HELLO_RETRY_INTERVAL,
    HELLO_TIMEOUT,
    InputState,
    KEEPALIVE_INTERVAL,
    MAX_FRAGMENT_MESSAGES,
    MAX_MESSAGE_BYTES,
    MAX_UDP_DATAGRAM_BYTES,
    PKT_ACK,
    PKT_DATA,
    PKT_DISCONNECT,
    PKT_FRAGMENT,
    PKT_HELLO,
    PKT_HELLO_ACK,
    PKT_KEEPALIVE,
    PlayerState,
    RELIABLE_MAX_RETRIES,
    RELIABLE_RESEND_INTERVAL,
)
